name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build documentation
        run: npm run docs:build

      - name: Build demo
        run: npm run build:demo --workspace=packages/use-normalized-keys

      - name: Build tools
        run: npm run build:tools --workspace=packages/use-normalized-keys

      - name: Create pages structure
        run: |
          mkdir -p dist
          # Copy docs as root
          cp -r docs/.vitepress/dist/* dist/
          # Copy demo to /demo subdirectory
          mkdir -p dist/demo
          cp -r packages/use-normalized-keys/dist-demo/* dist/demo/
          # Copy tools to /tools subdirectory  
          mkdir -p dist/tools
          cp -r packages/use-normalized-keys/dist-tools/* dist/tools/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4